version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      target: production
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - APPLICATION_PORT=3001
      - PGUSER=myuser
      - PGHOST=db
      - PGPASSWORD=mypassword
      - PGDATABASE=adwaiseo
      - PGPORT=5432
  db:
    image: postgis/postgis
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "adwaiseo", "-U", "myuser" ]
      interval : 5s
      timeout : 5s
      retries : 5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=adwaiseo
